import { type NextPage } from "next";
import Head from "next/head";
import Nav from "~/components/Nav";
import { api } from "~/utils/api";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Loader from "~/components/Loader";

const Dashboard: NextPage = () => {
  const router = useRouter();

  const { data: projects, isLoading: projectsLoading } =
    api.project.getAll.useQuery();

  useEffect(() => {
    // Redirect to first project if exists
    if (projects?.[0]) {
      void router.push(`/dashboard/${projects[0].id}`);
    }
  }, [projects, router]);

  if (projectsLoading || projects?.[0]) return <Loader />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-base-100">
        <div className="mx-auto max-w-6xl px-4">
          <Nav />
          <div className="my-6" />
          No projects
        </div>
      </main>
    </>
  );
};

export default Dashboard;
